#!/bin/bash

echo "=== Test de l'interface GUI avec support réseau ==="
echo ""
echo "Le binaire game_gui a été compilé avec succès !"
echo ""
echo "Fonctionnalités intégrées :"
echo "• Interface graphique GTK4"
echo "• Support réseau client-serveur"
echo "• Threading pour éviter de bloquer l'interface"
echo "• Protocole de communication identique au CLI"
echo ""
echo "Pour tester l'interface :"
echo "1. Lancez l'interface GUI : ./build/game_gui"
echo "2. L'interface démarre en mode local par défaut"
echo "3. Pour tester le réseau :"
echo "   - Sur une machine : lancez en mode serveur"
echo "   - Sur une autre : lancez en mode client"
echo ""
echo "Architecture réseau :"
echo "• Port par défaut : 8080"
echo "• Protocole : TCP avec messages de 4 octets"
echo "• Format des coups : 'A1A3' (de A1 vers A3)"
echo ""
echo "Compilation réussie avec les dépendances :"
echo "• GTK4 pour l'interface graphique"
echo "• pthread pour le threading"
echo "• Votre couche réseau existante (net.c)"
echo ""
